language: node_js

node_js:
  - "4"
  - "6"
  - "8"
  - "10"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

# Resolves `npm prune --production` bug in npm@5.3.0
# https://github.com/npm/npm/issues/17781
before_install:
  - npm install -g npm@5.4

script:
  - npm run build
  - npm run test-travis

  # Prune deps to just production and ensure we can build the site
  - npm prune --production
  - npm run build
