language: node_js

node_js:
  - "4"
  - "6"
  - "8"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

script:
  - npm run build
  - npm run test-travis

  # Prune deps to just production and ensure we can build the site
  - npm prune --production
  - npm run build
