language: node_js

node_js:
  - "8"
  - "10"

# Use container-based Travis infrastructure.
sudo: false

cache: yarn

branches:
  only:
    - master

# gets you chrome
addons:
  chrome: stable

# Resolves `npm prune --production` bug in npm@5.3.0
# https://github.com/npm/npm/issues/17781
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - yarn run build
  - yarn run check
